source $DOTFILES/zsh/plugins
plugins=(
	git 
	gcloud 
	zsh-autosuggestions 
	zsh-syntax-highlighting 
	fzf
	ssh-agent
)

source $DOTFILES/zsh/options
source $DOTFILES/zsh/variables
source $DOTFILES/zsh/alias
source $DOTFILES/zsh/binds
source $DOTFILES/zsh/functions
if [[ -e $DOTFILES/zsh/local ]];
then
#	source $DOTFILES/zsh/local
fi

source $ZSH/oh-my-zsh.sh
source $DOTFILES/zsh/autocomplete
