source $DOTFILES/zsh/plugins

plugins=(git gcloud zsh-autosuggestions zsh-syntax-highlighting fzf)

source $DOTFILES/zsh/options
source $DOTFILES/zsh/variables
source $ZSH/oh-my-zsh.sh
source $DOTFILES/zsh/autocomplete
source $DOTFILES/zsh/alias
source $DOTFILES/zsh/binds
source $DOTFILES/zsh/functions

if [[ -e $DOTFILES/zsh/local ]];
then
	source $DOTFILES/zsh/local
fi
